//! The per-tab decision behind "PATANYX held this page. Open anyway?", as a
//! pure state machine with no engine in it.
//!
//! WHY IT LIVES HERE RATHER THAN IN `state.rs`. Everything in this file is a
//! rule about what the user consented to, and every one of those rules is a
//! way the feature could become a hole instead of an exception. Kept pure,
//! they are provable under `cargo test` on a machine with no WebView2 and no
//! WebKitGTK -- the same reason `privacy::decide_request` is shaped the way it
//! is. The engine adapters call in; they do not reimplement any of this.
//!
//! THE PRECEDENT IS THE PLAIN-HTTP WARNING, deliberately. `insecure_pending`
//! already holds a navigation, shows a banner, and lets the user continue for
//! that tab and that host. This is the same shape with two additions the
//! ad-list case forces:
//!
//! - an `id` on the pending, because this banner survives a tab switch. The
//!   chrome renders from an async status push, so a switch can race the
//!   repaint and a click could otherwise answer a banner that now belongs to
//!   a different tab. `insecure_allow` does not need this: it reads the ACTIVE
//!   tab and confirms the host, which is enough when the banner cannot outlive
//!   the tab being looked at.
//! - a navigation generation, because the page we draw in place of the blocked
//!   one is itself a load, and without a generation it would clear the very
//!   warning it was raised for.
//!
//! WHAT CONSENT MEANS HERE, exactly: this tab may reach THIS ONE HOST despite
//! the ad and tracker list, until the tab's committed top-level host changes
//! or the tab goes away. It is not a site setting, it does not persist, it
//! does not cross tabs, and it lifts nothing except the ad-list rule.

use std::sync::atomic::{AtomicU64, Ordering};

/// Pending ids are unique across the PROCESS, not per tab.
///
/// That is the property that makes a racing click safe. Per-tab counters would
/// hand two tabs the same id 1, and a click that arrived after a tab switch
/// would match the wrong tab's pending and consent to a host the user never
/// read. Monotonic and never reused, so a stale click fails a comparison
/// rather than matching something new.
static NEXT_PENDING_ID: AtomicU64 = AtomicU64::new(1);

/// Whether this backend can except ONE host from the ad/tracker list for ONE
/// tab.
///
/// WebView2 decides per request in `decide_request`, so a single host can be
/// exempted cheaply. WebKitGTK enforces with a compiled content filter, where
/// the exception has to live INSIDE each shipped list and every grant and every
/// revocation costs a recompile of a 116k-rule list. Cut deliberately
/// 2026-09-15: Linux gets the held-page explanation and no button.
///
/// The chrome reads this through `tab_status` rather than deciding for itself,
/// so it cannot offer an action the engine has no path for.
pub const CAN_ALLOW: bool = cfg!(windows);

/// A per-process secret that marks OUR synthesized placeholder response on
/// Windows, so the integrity capture can tell it from a server document.
///
/// A fixed header name was not enough: any server can send a header, and a
/// page that sent `X-PATANYX-Held` on its own document could make the capture
/// skip it, then fetch its own URL again and have that response accepted as
/// the page's original bytes (review R-002, round 2). The VALUE is 16 random
/// bytes drawn once at startup, compared exactly on the way back in. A server
/// cannot know it, so a server cannot forge it.
pub fn held_nonce() -> &'static str {
    use std::sync::OnceLock;
    static NONCE: OnceLock<String> = OnceLock::new();
    NONCE.get_or_init(|| {
        let mut bytes = [0u8; 16];
        // A failure here means the OS entropy source is broken. An EMPTY
        // nonce is the signal to the emit side to NOT synthesize a placeholder
        // at all and fall through to the plain 403. The first draft served the
        // placeholder unmarked and called that "safe, nothing is skipped"; it
        // was the reverse. An unmarked placeholder is not skipped by the
        // capture, so browser-generated bytes would have been recorded as the
        // server's document (review R-002, round 3). No placeholder, no
        // capture risk.
        if getrandom::getrandom(&mut bytes).is_err() {
            return String::new();
        }
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    })
}

/// What the tab shows in place of the blocked document.
///
/// STATIC HTML ONLY, and that is a stated constraint rather than a current
/// accident. On WebKitGTK this is loaded with the blocked URL as its base so
/// the address bar stays on what the user typed instead of about:blank, which
/// makes the document SAME-ORIGIN with the listed host. On Windows the
/// synthesized 200 is served at that URL and has the same shape. Script here
/// would be script running on the tracker's origin. No script, no storage,
/// nothing that reads from that origin; the CSP says so to the engine and the
/// test below says so to the next editor.
///
/// It carries no copy. The banner in the chrome is where the explanation and
/// the actions live, because a held site cannot forge a control it does not
/// host. This page only has to be unmistakably not the site.
pub const PLACEHOLDER_HTML: &str = "<!doctype html><html><head><meta charset=\"utf-8\">\
<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'\">\
<title>PATANYX held this page</title>\
<style>html,body{margin:0;height:100%;background:#1c1c1e}</style>\
</head><body></body></html>";

/// The wire code for a refusal, which the chrome turns into a sentence.
pub fn refusal_code(r: ConsentRefusal) -> &'static str {
    match r {
        ConsentRefusal::NoPending => "adlist_no_pending",
        ConsentRefusal::WrongPending => "adlist_stale_banner",
        ConsentRefusal::HostMismatch => "adlist_host_mismatch",
        ConsentRefusal::NotListed => "adlist_not_listed",
    }
}

fn next_pending_id() -> u64 {
    NEXT_PENDING_ID.fetch_add(1, Ordering::Relaxed)
}

/// One held navigation, waiting on the user.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdlistPending {
    /// Process-unique. See `NEXT_PENDING_ID`.
    pub id: u64,
    /// The COMPLETE navigation URL, fragment included.
    ///
    /// Stored whole because it is what we resume, and because the fragment is
    /// the part an engine is most likely to drop: on Windows the intercepted
    /// request URI never carries it, so the navigation URL is the only place
    /// it survives. Resuming a URL that is nearly the one the user asked for
    /// is a quiet way to send them somewhere else.
    pub url: String,
    /// The host the banner names and the consent is scoped to.
    pub host: String,
    /// The tab's navigation generation when this was raised. A pending from an
    /// older generation is stale by definition: the user has moved on.
    pub nav_gen: u64,
    /// The HTTP method of the held navigation.
    ///
    /// Carried because consent resumes a URL and a URL has no body: a held
    /// form submission cannot be replayed, and the banner has to say so before
    /// the click rather than let the user find out after it.
    pub method: String,
}

/// Why a consent call was refused. Each is a real way the UI and the state can
/// disagree, and the caller turns them into distinct sentences rather than one
/// shrug: a user who clicked on a banner that had already gone needs to be told
/// something different from one whose host stopped being listed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConsentRefusal {
    /// Nothing is being held in this tab.
    NoPending,
    /// The click names a pending that is not the one outstanding: a stale
    /// banner, or one belonging to another tab.
    WrongPending,
    /// The click names a different host from the one the pending holds. The
    /// chrome is CONFIRMING what it drew, not choosing; a mismatch means the
    /// user read one thing and the state holds another.
    HostMismatch,
    /// The host is no longer on the list, re-checked at the moment of use.
    /// Consenting to an exception that is not needed would leave an override
    /// standing for a host nothing would have blocked.
    NotListed,
}

/// The per-tab machine. One of these lives on a Tab.
#[derive(Debug, Default)]
pub struct AdlistConsent {
    pending: Option<AdlistPending>,
    /// The single host this tab may reach despite the list. `Option`, not a
    /// set: consent is granted one banner at a time, and a set would quietly
    /// accumulate hosts for the life of the tab, which is the shape the
    /// malicious-host override has and the reason it is not the model here.
    override_host: Option<String>,
    nav_gen: u64,
}

/// A URL compared for identity: the fragment is dropped, since an in-page
/// link changes it without a navigation.
fn identity(url: &str) -> &str {
    match url.find('#') {
        Some(i) => &url[..i],
        None => url,
    }
}

impl AdlistConsent {
    /// Hold a navigation and raise the banner. Returns the new pending id.
    ///
    /// The caller has already established that this is a TOP-LEVEL document
    /// request to a listed host with blocking on and no override. Nothing in
    /// this module can check that, which is exactly why the caller must: a
    /// subframe that reached here would raise a banner for a host the user
    /// never navigated to, and the "Open anyway" under it would be real.
    pub fn raise(&mut self, url: &str, host: &str, method: &str) -> u64 {
        let id = next_pending_id();
        self.pending = Some(AdlistPending {
            id,
            url: url.to_string(),
            host: host.to_string(),
            nav_gen: self.nav_gen,
            method: method.to_string(),
        });
        id
    }

    pub fn pending(&self) -> Option<&AdlistPending> {
        self.pending.as_ref()
    }

    pub fn override_host(&self) -> Option<&str> {
        self.override_host.as_deref()
    }

    /// A top-level navigation started, to `url`.
    ///
    /// Bumps the generation and clears the banner -- unless the navigation is
    /// to the very URL that is held. That is our placeholder arriving: on
    /// WebKitGTK it is a separate `load_html` at the failing URI, on WebView2
    /// it is the held navigation itself completing with our synthesized body.
    /// Either way it is a load but not the user going anywhere, and clearing
    /// on it would take down the very warning it exists to display.
    ///
    /// DECIDED BY URL EQUALITY, NOT BY A "NEXT LOAD IS OURS" FLAG, and the
    /// difference matters. A flag is consumed by the next navigation, and on
    /// WebView2 there is no next navigation for the placeholder -- the held
    /// one simply completes -- so the flag would survive to swallow the
    /// user's next real navigation and leave a stale banner up. Equality has
    /// no such state. A page that navigates the top frame to the held URL
    /// gains nothing: it is the URL the user was already held on.
    pub fn on_top_level_navigation(&mut self, url: &str) {
        if let Some(p) = &self.pending {
            if identity(&p.url) == identity(url) {
                return;
            }
        }
        self.nav_gen = self.nav_gen.wrapping_add(1);
        self.pending = None;
    }

    /// The tab committed a new top-level host.
    ///
    /// THIS IS WHERE CONSENT ENDS, and it is the half that is easy to leave
    /// out: granting an override is visible work, ending one is not, and an
    /// override that is never revoked silently outlives the sentence the user
    /// agreed to. Returns whether an override was actually dropped, because on
    /// WebKitGTK the caller must then recompile the filter lists WITHOUT the
    /// exception. Leaving it compiled in would keep the host reachable in this
    /// tab for the rest of its life with no banner and no second consent.
    pub fn on_committed_host(&mut self, host: &str) -> bool {
        match self.override_host.as_deref() {
            Some(current) if current != host => {
                self.override_host = None;
                true
            }
            _ => false,
        }
    }

    /// End the override outright, for a navigation that leaves the host
    /// without arriving at another one. about:blank has no host, and a
    /// revocation keyed only on "the host changed" let it keep the override
    /// alive. Returns whether one was dropped, for the same reason
    /// `on_committed_host` does.
    pub fn end_override(&mut self) -> bool {
        self.override_host.take().is_some()
    }

    /// Take the banner down without answering it. Used when the reason for
    /// the hold is gone: the user switched blocking off, as the banner told
    /// them they could.
    /// Put back a record that `allow` consumed, when what followed the
    /// consent could not start. Same id, same method, so the banner the user
    /// still sees keeps working on retry and a held POST stays a POST.
    /// Re-raising instead allocated a new id nobody had been told about, and
    /// read the method after it was gone, so every failed POST hold came back
    /// as GET (review R-003, round 4). Never overwrites a newer record.
    pub fn restore(&mut self, record: AdlistPending) {
        if self.pending.is_none() {
            self.pending = Some(record);
        }
    }

    pub fn clear_pending(&mut self) {
        self.pending = None;
    }

    /// The user answered "Open anyway".
    ///
    /// `still_listed` is re-evaluated by the caller AT THIS MOMENT rather than
    /// trusted from when the banner was raised. `shown_host` is what the
    /// chrome says it drew: a CONFIRMATION, never a selection. No value any
    /// caller can pass makes this resume a URL that was not already pending,
    /// which is what stops it becoming an open-anything primitive.
    ///
    /// Returns the complete URL to resume. The pending is cleared only once
    /// every check has passed: a refused click must leave the banner up so the
    /// user can try again, rather than dismissing it and looking like it
    /// worked.
    pub fn allow(
        &mut self,
        pending_id: u64,
        shown_host: &str,
        still_listed: bool,
    ) -> Result<String, ConsentRefusal> {
        let pending = self.pending.as_ref().ok_or(ConsentRefusal::NoPending)?;
        if pending.id != pending_id {
            return Err(ConsentRefusal::WrongPending);
        }
        if !shown_host.eq_ignore_ascii_case(&pending.host) {
            return Err(ConsentRefusal::HostMismatch);
        }
        if !still_listed {
            return Err(ConsentRefusal::NotListed);
        }
        let pending = self.pending.take().expect("checked above");
        self.override_host = Some(pending.host);
        Ok(pending.url)
    }

    /// The user answered "Dismiss". Same id discipline as `allow`: a stale
    /// click must not silently clear a banner raised for something else.
    pub fn dismiss(&mut self, pending_id: u64) -> Result<(), ConsentRefusal> {
        let pending = self.pending.as_ref().ok_or(ConsentRefusal::NoPending)?;
        if pending.id != pending_id {
            return Err(ConsentRefusal::WrongPending);
        }
        self.pending = None;
        Ok(())
    }
}

/// What a WebKitGTK `load-failed` means for this feature.
///
/// The Linux engine enforces with a content filter, so a blocked top-level
/// document arrives here as a failure rather than as a refused request. The
/// classifier is the only thing standing between "the ad list held this page"
/// and every other reason a load can fail, and it must not claim any of them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LoadFailure {
    /// The ad/tracker list held a page the user navigated to. Raise the banner.
    Adlist,
    /// The tab is frozen, so the filter that refused this is the FREEZE filter.
    ///
    /// Checked BEFORE the ad list, because a frozen tab blocks everything and
    /// reporting that as an ad-list block would offer an "Open anyway" that
    /// lifts the wrong thing: the user would consent to an ad-list exception
    /// and still be frozen, and the page still would not load. The banner has
    /// to name the reason that is actually stopping them.
    Frozen,
    /// Not ours. Network errors, TLS failures, refused connections and every
    /// other policy error keep whatever handling they already had.
    Other,
}

/// WebKit's error domain for a policy refusal, and the code a content-filter
/// block arrives with. MEASURED on WebKitGTK 2.52.6, 2026-09-15, rather than
/// read from a header: the failure reports domain `WebKitPolicyError` with
/// code 104 and the message "The URL was blocked by a content blocker".
pub const WEBKIT_POLICY_ERROR: &str = "WebKitPolicyError";
pub const WEBKIT_BLOCKED_BY_CONTENT_BLOCKER: i32 = 104;

/// Decide what a load failure was, from facts the caller has already gathered.
///
/// Every input is a fact rather than a judgement, so the rule is visible here
/// instead of spread across the engine adapter. `listed` is re-evaluated by
/// the caller at this moment; `overridden` means this tab already consented to
/// the host, in which case the filter should not have refused it and something
/// is wrong in a direction this function must not paper over: it reports
/// `Other` so the failure surfaces as itself rather than as a second banner
/// for a host the user already allowed.
pub fn classify_load_failure(
    domain: &str,
    code: i32,
    listed: bool,
    block_ads: bool,
    frozen: bool,
    overridden: bool,
) -> LoadFailure {
    if domain != WEBKIT_POLICY_ERROR || code != WEBKIT_BLOCKED_BY_CONTENT_BLOCKER {
        return LoadFailure::Other;
    }
    if frozen {
        return LoadFailure::Frozen;
    }
    if !block_ads || !listed || overridden {
        return LoadFailure::Other;
    }
    LoadFailure::Adlist
}

/// Guards a filter recompile that finishes after the world moved on.
///
/// WHY THIS IS NOT PARANOIA. Compiling the override into the tracking list
/// takes ~0.5 s (measured 2026-09-15: 116,386 rules in 497 ms), and the resume
/// is issued from the completion callback. Half a second is long enough for the
/// user to navigate again, close the tab, or end the consent by leaving the
/// host. A callback that lands afterwards and installs its filters anyway is
/// the worst kind of bug in this feature: it reinstates an exception for a
/// consent that already ended, silently, with no banner and nothing on screen
/// that is wrong.
///
/// Every asynchronous step in the override path carries the generation it was
/// started under, and does nothing if the tab has moved past it. REVOCATION
/// BUMPS IT TOO, not just grants: a grant compile that lands after the user
/// left the consented host must be discarded, and if only grants advanced the
/// counter it would be installed instead.
#[derive(Debug, Default)]
pub struct FilterGeneration {
    current: u64,
    alive: bool,
}

impl FilterGeneration {
    pub fn new() -> Self {
        Self {
            current: 0,
            alive: true,
        }
    }

    /// Start a unit of async work; the returned token is what the callback
    /// must present.
    pub fn begin(&mut self) -> u64 {
        self.current = self.current.wrapping_add(1);
        self.current
    }

    /// Anything that invalidates in-flight work: a new navigation, consent
    /// ending, a second grant superseding the first.
    pub fn invalidate(&mut self) {
        self.current = self.current.wrapping_add(1);
    }

    /// The tab is gone. Nothing may be installed into it again, ever, and this
    /// is separate from the counter because a wrapped counter could otherwise
    /// coincide with a stale token from a tab that no longer exists.
    pub fn close(&mut self) {
        self.alive = false;
    }

    /// May a completion callback holding `token` act?
    pub fn may_apply(&self, token: u64) -> bool {
        self.alive && token == self.current
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const URL: &str = "https://ipaddress.com/lookup?q=1#result";
    const HOST: &str = "ipaddress.com";

    fn held() -> (AdlistConsent, u64) {
        let mut c = AdlistConsent::default();
        let id = c.raise(URL, HOST, "GET");
        (c, id)
    }

    #[test]
    fn allow_resumes_the_complete_url_including_the_fragment() {
        let (mut c, id) = held();
        assert_eq!(c.allow(id, HOST, true), Ok(URL.to_string()));
        assert_eq!(c.override_host(), Some(HOST));
        assert!(c.pending().is_none(), "consent must clear the banner");
    }

    /// The racing-click case, and the reason the id exists at all. The chrome
    /// renders from an async push, so a tab switch can land between the paint
    /// and the click.
    #[test]
    fn a_click_naming_another_tabs_pending_is_refused() {
        let (mut c, id) = held();
        assert_eq!(c.allow(id + 1, HOST, true), Err(ConsentRefusal::WrongPending));
        assert!(
            c.pending().is_some(),
            "a refused click cleared the banner; the user cannot retry and it \
             looks like it worked"
        );
        assert_eq!(c.override_host(), None, "a refused click granted an override");
    }

    /// Ids are process-wide, so two tabs never hold the same one. A per-tab
    /// counter would make this test pass and the real race still happen.
    #[test]
    fn pending_ids_are_unique_across_tabs() {
        let mut a = AdlistConsent::default();
        let mut b = AdlistConsent::default();
        assert_ne!(a.raise(URL, HOST, "GET"), b.raise(URL, HOST, "GET"));
    }

    /// The chrome confirms the host it drew. If the two disagree the user read
    /// one thing and the state holds another.
    #[test]
    fn a_host_the_banner_did_not_show_is_refused() {
        let (mut c, id) = held();
        assert_eq!(
            c.allow(id, "whatismyip.com", true),
            Err(ConsentRefusal::HostMismatch)
        );
        assert_eq!(c.override_host(), None);
        assert!(c.pending().is_some());
    }

    #[test]
    fn host_comparison_ignores_case_because_hosts_are_case_insensitive() {
        let (mut c, id) = held();
        assert!(c.allow(id, "IPAddress.COM", true).is_ok());
    }

    /// Re-checked at the moment of use. A list refresh between the banner and
    /// the click must not leave an override standing for a host nothing would
    /// have blocked.
    #[test]
    fn a_host_no_longer_listed_is_refused() {
        let (mut c, id) = held();
        assert_eq!(c.allow(id, HOST, false), Err(ConsentRefusal::NotListed));
        assert_eq!(c.override_host(), None);
    }

    #[test]
    fn consent_without_a_banner_is_refused() {
        let mut c = AdlistConsent::default();
        assert_eq!(c.allow(1, HOST, true), Err(ConsentRefusal::NoPending));
    }

    /// The placeholder is a load at the held URL, but it is not the user
    /// going anywhere. On WebView2 it is the held navigation itself completing.
    #[test]
    fn a_load_of_the_held_url_does_not_clear_the_banner() {
        let (mut c, id) = held();
        c.on_top_level_navigation(URL);
        assert_eq!(
            c.pending().map(|p| p.id),
            Some(id),
            "drawing the held page cleared the warning it was drawn for"
        );
        // Fragment differences are still the same page.
        c.on_top_level_navigation("https://ipaddress.com/lookup?q=1#other");
        assert_eq!(c.pending().map(|p| p.id), Some(id));
    }

    /// No flag, so nothing to consume: a second load of the held URL is still
    /// the held page, and the FIRST load elsewhere clears it. A flag-based
    /// scheme would have been eaten by the placeholder on one engine and by
    /// the user's next navigation on the other.
    #[test]
    fn leaving_the_held_url_clears_the_banner_however_many_placeholder_loads_preceded_it() {
        let (mut c, _) = held();
        c.on_top_level_navigation(URL);
        c.on_top_level_navigation(URL);
        assert!(c.pending().is_some());
        c.on_top_level_navigation("https://news.example/");
        assert!(c.pending().is_none(), "a real navigation left a stale banner up");
    }

    #[test]
    fn a_real_navigation_clears_the_banner_and_advances_the_generation() {
        let (mut c, _) = held();
        let before = c.pending().expect("held").nav_gen;
        c.on_top_level_navigation("https://news.example/");
        assert!(c.pending().is_none());
        assert_ne!(before, c.nav_gen, "the generation did not advance");
    }

    /// THE GAP THIS TEST EXISTS FOR. Granting an override is visible work;
    /// ending one is not. Found by a red-team pass on 2026-09-15: the design
    /// stated the lifetime and stated the recompile that ADDS the exception,
    /// and never stated the one that removes it. On WebKitGTK that leaves the
    /// host reachable in the tab for the rest of its life.
    #[test]
    fn leaving_the_consented_host_ends_the_override_and_says_so() {
        let (mut c, id) = held();
        c.allow(id, HOST, true).expect("allow");
        assert_eq!(c.override_host(), Some(HOST));

        // Landing on the consented host itself is not leaving it.
        assert!(!c.on_committed_host(HOST));
        assert_eq!(c.override_host(), Some(HOST));

        // Going elsewhere ends it, and reports that it did so the caller
        // knows a filter recompile is owed.
        assert!(
            c.on_committed_host("news.example"),
            "leaving the host did not report that an override was dropped; \
             the caller never recompiles and the exception stays installed"
        );
        assert_eq!(c.override_host(), None);

        // Nothing to drop the second time: no pointless recompile.
        assert!(!c.on_committed_host("news.example"));
    }

    /// R-003. A navigation to no host at all is still leaving the host.
    #[test]
    fn leaving_for_a_hostless_page_ends_the_override_too() {
        let (mut c, id) = held();
        c.allow(id, HOST, true).expect("allow");
        assert!(c.end_override(), "an override was not reported dropped");
        assert_eq!(c.override_host(), None);
        assert!(!c.end_override(), "a second end reported a drop with nothing to drop");
    }

    /// R-004. The banner says blocking can be switched off; doing so must take
    /// the banner down, or the real page loads under a warning that it did not.
    #[test]
    fn clearing_takes_the_banner_down_without_granting() {
        let (mut c, _) = held();
        c.clear_pending();
        assert!(c.pending().is_none());
        assert_eq!(c.override_host(), None, "clearing granted an override");
    }

    /// The marker is a secret, not a name. Same length every time, hex, and
    /// stable within a process so the emit side and the check side agree.
    #[test]
    fn the_held_nonce_is_secret_shaped_and_stable() {
        let a = held_nonce();
        let b = held_nonce();
        assert_eq!(a, b, "the nonce changed between reads; the check would never match");
        assert_eq!(a.len(), 32, "16 random bytes as hex");
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn dismiss_takes_the_banner_down_and_grants_nothing() {
        let (mut c, id) = held();
        assert_eq!(c.dismiss(id), Ok(()));
        assert!(c.pending().is_none());
        assert_eq!(c.override_host(), None, "Dismiss granted an override");
    }

    #[test]
    fn a_stale_dismiss_leaves_the_current_banner_alone() {
        let (mut c, id) = held();
        assert_eq!(c.dismiss(id + 1), Err(ConsentRefusal::WrongPending));
        assert!(c.pending().is_some());
    }

    /// The placeholder is same-origin with the listed host on both engines,
    /// so it may carry nothing that could run or read there.
    #[test]
    fn the_placeholder_is_inert() {
        let h = PLACEHOLDER_HTML.to_ascii_lowercase();
        assert!(!h.contains("<script"), "script on the listed host's origin");
        assert!(!h.contains("onload") && !h.contains("onerror"), "inline handler");
        assert!(h.contains("default-src 'none'"), "no CSP telling the engine the same");
        assert!(!h.contains("<a "), "a link would navigate on that origin");
    }

    // ---- T6: a compile that finishes after the world moved on -------------

    #[test]
    fn a_compile_that_finishes_in_time_is_applied() {
        let mut g = FilterGeneration::new();
        let t = g.begin();
        assert!(g.may_apply(t));
    }

    /// Consent for A, then the user navigates to B, then A's compile lands.
    /// Installing it now would put an exception in the filters for a page the
    /// user is no longer on.
    #[test]
    fn a_compile_superseded_by_a_new_navigation_is_discarded() {
        let mut g = FilterGeneration::new();
        let stale = g.begin();
        g.invalidate(); // the navigation to B
        assert!(
            !g.may_apply(stale),
            "a filter set compiled for the previous page was installed anyway"
        );
    }

    /// The case the generation exists for, and the one the design missed until
    /// a red-team pass found it: REVOCATION must invalidate too. If only grants
    /// advanced the counter, a grant compile that lands after the user left the
    /// consented host would still be installed, reinstating an exception for a
    /// consent that had already ended.
    #[test]
    fn a_grant_that_lands_after_the_consent_ended_is_discarded() {
        let mut g = FilterGeneration::new();
        let grant = g.begin();
        g.invalidate(); // on_committed_host dropped the override
        assert!(
            !g.may_apply(grant),
            "a grant compile landed after consent ended and reinstalled the \
             exception; the host stays reachable with no banner"
        );
    }

    #[test]
    fn nothing_is_applied_to_a_closed_tab() {
        let mut g = FilterGeneration::new();
        let t = g.begin();
        g.close();
        assert!(!g.may_apply(t), "filters were installed into a closed tab");
    }

    /// A closed tab stays closed. Without the separate flag, a wrapped counter
    /// could coincide with a token from a tab that no longer exists.
    #[test]
    fn a_closed_tab_cannot_be_revived_by_a_matching_token() {
        let mut g = FilterGeneration::new();
        g.close();
        let t = g.begin();
        assert!(!g.may_apply(t));
    }

    /// Two grants in a row: only the newer may land, whichever order the
    /// compiles finish in.
    #[test]
    fn an_older_compile_cannot_overwrite_a_newer_one() {
        let mut g = FilterGeneration::new();
        let first = g.begin();
        let second = g.begin();
        assert!(!g.may_apply(first), "the older compile was still applied");
        assert!(g.may_apply(second));
    }

    // ---- T4: the WebKitGTK load-failure classifier -----------------------

    fn listed_block() -> LoadFailure {
        classify_load_failure(WEBKIT_POLICY_ERROR, 104, true, true, false, false)
    }

    #[test]
    fn a_content_blocker_refusal_of_a_listed_host_is_ours() {
        assert_eq!(listed_block(), LoadFailure::Adlist);
    }

    /// The measured values, pinned. A future engine that changes either must
    /// fail here rather than silently stop raising the banner.
    #[test]
    fn the_domain_and_code_are_the_measured_ones() {
        assert_eq!(WEBKIT_POLICY_ERROR, "WebKitPolicyError");
        assert_eq!(WEBKIT_BLOCKED_BY_CONTENT_BLOCKER, 104);
    }

    #[test]
    fn other_domains_and_codes_are_left_alone() {
        for (d, c) in [
            ("WebKitNetworkError", 104),
            (WEBKIT_POLICY_ERROR, 102),
            ("WebKitPolicyError ", 104),
            ("", 0),
        ] {
            assert_eq!(
                classify_load_failure(d, c, true, true, false, false),
                LoadFailure::Other,
                "{d:?}/{c} was claimed as an ad-list block"
            );
        }
    }

    /// A frozen tab blocks everything. Reporting that as an ad-list block
    /// would offer an Open anyway that lifts the wrong thing, and the page
    /// still would not load after the user consented.
    #[test]
    fn a_frozen_tab_is_attributed_to_the_freeze_not_the_list() {
        assert_eq!(
            classify_load_failure(WEBKIT_POLICY_ERROR, 104, true, true, true, false),
            LoadFailure::Frozen
        );
        // ...even when the host is not listed at all: the freeze is still the
        // reason, and it is still not ours.
        assert_eq!(
            classify_load_failure(WEBKIT_POLICY_ERROR, 104, false, true, true, false),
            LoadFailure::Frozen
        );
    }

    #[test]
    fn an_unlisted_host_or_blocking_switched_off_is_not_ours() {
        assert_eq!(
            classify_load_failure(WEBKIT_POLICY_ERROR, 104, false, true, false, false),
            LoadFailure::Other
        );
        assert_eq!(
            classify_load_failure(WEBKIT_POLICY_ERROR, 104, true, false, false, false),
            LoadFailure::Other
        );
    }

    /// An already-consented host should not have been refused. Raising a
    /// second banner for it would ask the user to consent to what they just
    /// consented to, and would hide whatever really went wrong.
    #[test]
    fn a_host_this_tab_already_allowed_does_not_raise_a_second_banner() {
        assert_eq!(
            classify_load_failure(WEBKIT_POLICY_ERROR, 104, true, true, false, true),
            LoadFailure::Other
        );
    }

    /// Consent is one host. A second banner must not silently widen it.
    #[test]
    fn a_second_consent_replaces_the_first_rather_than_accumulating() {
        let (mut c, id) = held();
        c.allow(id, HOST, true).expect("first");
        let id2 = c.raise("https://whatismyip.com/", "whatismyip.com", "GET");
        c.allow(id2, "whatismyip.com", true).expect("second");
        assert_eq!(
            c.override_host(),
            Some("whatismyip.com"),
            "the tab now reaches two listed hosts from one banner each; \
             consent must not accumulate"
        );
    }
    /// R-003, round 4. A consent whose navigation failed to start is restored
    /// intact: the id the banner is still showing works again, and the
    /// method survives.
    #[test]
    fn a_restored_record_keeps_its_id_and_method() {
        let mut c = AdlistConsent::default();
        let id = c.raise("https://ipaddress.com/lookup", "ipaddress.com", "POST");
        let record = c.pending().cloned().expect("raised");
        assert!(c.allow(id, "ipaddress.com", true).is_ok());
        assert!(c.pending().is_none(), "precondition: allow consumed the record");
        c.end_override();
        c.restore(record);
        let back = c.pending().expect("restored");
        assert_eq!(back.id, id, "the id the banner still shows must work on retry");
        assert_eq!(back.method, "POST", "a failed POST hold came back as GET");
        assert!(c.allow(id, "ipaddress.com", true).is_ok(), "retry with the OLD id was refused as stale");
    }

    /// A restore must never clobber a record raised in the meantime.
    #[test]
    fn a_restore_never_overwrites_a_newer_record() {
        let mut c = AdlistConsent::default();
        let old_id = c.raise("https://ipaddress.com/a", "ipaddress.com", "GET");
        let old = c.pending().cloned().unwrap();
        c.clear_pending();
        let new_id = c.raise("https://whatismyip.com/", "whatismyip.com", "GET");
        c.restore(old);
        assert_eq!(c.pending().unwrap().id, new_id);
        assert_ne!(c.pending().unwrap().id, old_id);
    }
}
