// GENERATED by scripts/gen-language-registry.py. Do not edit by hand.
//
// The pairs below are the ones Mozilla actually publishes. Editing this
// file to add a pair would offer a language that can never be installed,
// because no model exists to fetch.

/// A language this build can name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Language {
    pub code: &'static str,
    pub name: &'static str,
}

/// Every language appearing in at least one usable pair (68).
pub const LANGUAGES: &[Language] = &[
    Language { code: "af", name: "Afrikaans" },
    Language { code: "ar", name: "Arabic" },
    Language { code: "az", name: "Azerbaijani" },
    Language { code: "bg", name: "Bulgarian" },
    Language { code: "bn", name: "Bengali" },
    Language { code: "bs", name: "Bosnian" },
    Language { code: "ca", name: "Catalan" },
    Language { code: "cs", name: "Czech" },
    Language { code: "da", name: "Danish" },
    Language { code: "de", name: "German" },
    Language { code: "el", name: "Greek" },
    Language { code: "en", name: "English" },
    Language { code: "eo", name: "Esperanto" },
    Language { code: "es", name: "Spanish" },
    Language { code: "et", name: "Estonian" },
    Language { code: "eu", name: "Basque" },
    Language { code: "fa", name: "Persian" },
    Language { code: "fi", name: "Finnish" },
    Language { code: "fr", name: "French" },
    Language { code: "frm", name: "Middle French" },
    Language { code: "ga", name: "Irish" },
    Language { code: "gl", name: "Galician" },
    Language { code: "gu", name: "Gujarati" },
    Language { code: "ha", name: "Hausa" },
    Language { code: "he", name: "Hebrew" },
    Language { code: "hi", name: "Hindi" },
    Language { code: "hr", name: "Croatian" },
    Language { code: "ht", name: "Haitian Creole" },
    Language { code: "hu", name: "Hungarian" },
    Language { code: "id", name: "Indonesian" },
    Language { code: "ig", name: "Igbo" },
    Language { code: "is", name: "Icelandic" },
    Language { code: "it", name: "Italian" },
    Language { code: "ja", name: "Japanese" },
    Language { code: "ka", name: "Georgian" },
    Language { code: "kn", name: "Kannada" },
    Language { code: "ko", name: "Korean" },
    Language { code: "la", name: "Latin" },
    Language { code: "lt", name: "Lithuanian" },
    Language { code: "lv", name: "Latvian" },
    Language { code: "mg", name: "Malagasy" },
    Language { code: "mk", name: "Macedonian" },
    Language { code: "ml", name: "Malayalam" },
    Language { code: "mr", name: "Marathi" },
    Language { code: "ms", name: "Malay" },
    Language { code: "nb", name: "Norwegian Bokmål" },
    Language { code: "nl", name: "Dutch" },
    Language { code: "ny", name: "Chichewa" },
    Language { code: "pl", name: "Polish" },
    Language { code: "pt", name: "Portuguese" },
    Language { code: "ro", name: "Romanian" },
    Language { code: "ru", name: "Russian" },
    Language { code: "rw", name: "Kinyarwanda" },
    Language { code: "sk", name: "Slovak" },
    Language { code: "sl", name: "Slovenian" },
    Language { code: "sq", name: "Albanian" },
    Language { code: "sr", name: "Serbian" },
    Language { code: "sv", name: "Swedish" },
    Language { code: "ta", name: "Tamil" },
    Language { code: "te", name: "Telugu" },
    Language { code: "th", name: "Thai" },
    Language { code: "tl", name: "Tagalog" },
    Language { code: "tr", name: "Turkish" },
    Language { code: "uk", name: "Ukrainian" },
    Language { code: "ur", name: "Urdu" },
    Language { code: "vi", name: "Vietnamese" },
    Language { code: "zh-Hans", name: "Chinese (Simplified)" },
    Language { code: "zh-Hant", name: "Chinese (Traditional)" },
];

/// Every usable translation direction (106): a stable
/// {model, lex, vocab} version exists upstream and both ends are namable.
///
/// One row per pair: token, source, target, chosen upstream version,
/// approximate download size in bytes. The TOKEN is the wire/path/URL
/// form; source and target are carried alongside precisely so that
/// nothing ever has to SPLIT a token -- "en-zh-Hans" cannot be split
/// unambiguously, and a registry lookup can never get it wrong.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pair {
    pub token: &'static str,
    pub from: &'static str,
    pub to: &'static str,
    pub upstream_version: &'static str,
    pub approx_bytes: u64,
    /// "joint" (one vocab.spm) or "split" (srcvocab + trgvocab).
    /// Decides how many parts the pack container carries, and
    /// how many vocabularies the engine is handed.
    pub vocab: &'static str,
    /// 1 = free (Mozilla set); 2 = Premium (OPUS-MT supplemental).
    pub tier: u8,
    /// "mozilla" or "opus-mt": which upstream the pack derives from.
    pub source: &'static str,
}

pub const PAIRS: &[Pair] = &[
    Pair { token: "af-en", from: "af", to: "en", upstream_version: "2.0", approx_bytes: 36453786, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ar-en", from: "ar", to: "en", upstream_version: "2.2", approx_bytes: 37049022, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "bg-en", from: "bg", to: "en", upstream_version: "2.0", approx_bytes: 36840189, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "bn-en", from: "bn", to: "en", upstream_version: "1.0", approx_bytes: 22915947, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "bs-en", from: "bs", to: "en", upstream_version: "2.0", approx_bytes: 37534530, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ca-en", from: "ca", to: "en", upstream_version: "2.0", approx_bytes: 36731612, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "cs-en", from: "cs", to: "en", upstream_version: "2.0", approx_bytes: 37367529, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "da-en", from: "da", to: "en", upstream_version: "1.0", approx_bytes: 22426481, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "de-en", from: "de", to: "en", upstream_version: "2.0", approx_bytes: 37317656, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "el-en", from: "el", to: "en", upstream_version: "1.1", approx_bytes: 22331871, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-af", from: "en", to: "af", upstream_version: "2.0", approx_bytes: 35564322, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ar", from: "en", to: "ar", upstream_version: "2.2", approx_bytes: 35565070, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-az", from: "en", to: "az", upstream_version: "1.0", approx_bytes: 21309164, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-bg", from: "en", to: "bg", upstream_version: "2.0", approx_bytes: 35560217, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-bn", from: "en", to: "bn", upstream_version: "1.0", approx_bytes: 21329765, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-bs", from: "en", to: "bs", upstream_version: "2.0", approx_bytes: 35599859, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ca", from: "en", to: "ca", upstream_version: "2.0", approx_bytes: 36716532, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-cs", from: "en", to: "cs", upstream_version: "2.0", approx_bytes: 35949377, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-da", from: "en", to: "da", upstream_version: "1.0", approx_bytes: 21801188, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-de", from: "en", to: "de", upstream_version: "2.1", approx_bytes: 36719532, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-el", from: "en", to: "el", upstream_version: "1.0", approx_bytes: 20893943, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-es", from: "en", to: "es", upstream_version: "2.1", approx_bytes: 36576277, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-et", from: "en", to: "et", upstream_version: "2.0", approx_bytes: 35867729, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-eu", from: "en", to: "eu", upstream_version: "2.0", approx_bytes: 35532187, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-fa", from: "en", to: "fa", upstream_version: "1.1", approx_bytes: 21615516, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-fi", from: "en", to: "fi", upstream_version: "2.0", approx_bytes: 35870649, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-fr", from: "en", to: "fr", upstream_version: "2.0", approx_bytes: 36749127, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-gl", from: "en", to: "gl", upstream_version: "2.1", approx_bytes: 35396493, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-gu", from: "en", to: "gu", upstream_version: "1.0", approx_bytes: 21285646, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-he", from: "en", to: "he", upstream_version: "1.0", approx_bytes: 21052116, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-hi", from: "en", to: "hi", upstream_version: "1.0", approx_bytes: 21571231, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-hr", from: "en", to: "hr", upstream_version: "1.0", approx_bytes: 21257882, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-hu", from: "en", to: "hu", upstream_version: "2.0", approx_bytes: 35858196, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-id", from: "en", to: "id", upstream_version: "1.0", approx_bytes: 21429690, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-is", from: "en", to: "is", upstream_version: "2.0", approx_bytes: 36209342, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-it", from: "en", to: "it", upstream_version: "2.1", approx_bytes: 36507703, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ja", from: "en", to: "ja", upstream_version: "2.3", approx_bytes: 49601566, vocab: "split", tier: 1, source: "mozilla" },
    Pair { token: "en-kn", from: "en", to: "kn", upstream_version: "1.0", approx_bytes: 21014535, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ko", from: "en", to: "ko", upstream_version: "2.1", approx_bytes: 51906032, vocab: "split", tier: 1, source: "mozilla" },
    Pair { token: "en-lt", from: "en", to: "lt", upstream_version: "2.1", approx_bytes: 35790254, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-lv", from: "en", to: "lv", upstream_version: "2.1", approx_bytes: 35737170, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ml", from: "en", to: "ml", upstream_version: "1.0", approx_bytes: 20783011, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-mr", from: "en", to: "mr", upstream_version: "2.0", approx_bytes: 35302839, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ms", from: "en", to: "ms", upstream_version: "1.0", approx_bytes: 21879919, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-nb", from: "en", to: "nb", upstream_version: "2.0", approx_bytes: 22177813, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-nl", from: "en", to: "nl", upstream_version: "2.1", approx_bytes: 36400119, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-pl", from: "en", to: "pl", upstream_version: "2.1", approx_bytes: 35923451, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-pt", from: "en", to: "pt", upstream_version: "2.1", approx_bytes: 36348853, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ro", from: "en", to: "ro", upstream_version: "1.0", approx_bytes: 21682453, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ru", from: "en", to: "ru", upstream_version: "2.1", approx_bytes: 35240782, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-sk", from: "en", to: "sk", upstream_version: "2.1", approx_bytes: 35727023, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-sl", from: "en", to: "sl", upstream_version: "2.1", approx_bytes: 35793299, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-sr", from: "en", to: "sr", upstream_version: "2.0", approx_bytes: 35026482, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-sv", from: "en", to: "sv", upstream_version: "1.0", approx_bytes: 21883099, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ta", from: "en", to: "ta", upstream_version: "2.0", approx_bytes: 35405968, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-te", from: "en", to: "te", upstream_version: "1.0", approx_bytes: 21029631, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-th", from: "en", to: "th", upstream_version: "2.0", approx_bytes: 35571916, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-tr", from: "en", to: "tr", upstream_version: "1.0", approx_bytes: 21201144, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-uk", from: "en", to: "uk", upstream_version: "2.2", approx_bytes: 35538228, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-ur", from: "en", to: "ur", upstream_version: "2.0", approx_bytes: 35472108, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-vi", from: "en", to: "vi", upstream_version: "2.0", approx_bytes: 36944671, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "en-zh-hans", from: "en", to: "zh-Hans", upstream_version: "2.2", approx_bytes: 51934991, vocab: "split", tier: 1, source: "mozilla" },
    Pair { token: "en-zh-hant", from: "en", to: "zh-Hant", upstream_version: "2.0", approx_bytes: 49462340, vocab: "split", tier: 1, source: "mozilla" },
    Pair { token: "es-en", from: "es", to: "en", upstream_version: "2.0", approx_bytes: 37014089, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "et-en", from: "et", to: "en", upstream_version: "2.0", approx_bytes: 37005329, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "eu-en", from: "eu", to: "en", upstream_version: "2.1", approx_bytes: 36126707, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "fa-en", from: "fa", to: "en", upstream_version: "1.0", approx_bytes: 21880624, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "fi-en", from: "fi", to: "en", upstream_version: "2.0", approx_bytes: 37575689, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "fr-en", from: "fr", to: "en", upstream_version: "2.0", approx_bytes: 37200311, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "gl-en", from: "gl", to: "en", upstream_version: "2.1", approx_bytes: 36756406, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "gu-en", from: "gu", to: "en", upstream_version: "1.0", approx_bytes: 22304030, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "he-en", from: "he", to: "en", upstream_version: "1.0", approx_bytes: 22622256, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "hi-en", from: "hi", to: "en", upstream_version: "1.0", approx_bytes: 22672471, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "hr-en", from: "hr", to: "en", upstream_version: "1.0", approx_bytes: 21797290, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "hu-en", from: "hu", to: "en", upstream_version: "1.0", approx_bytes: 23124073, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "id-en", from: "id", to: "en", upstream_version: "1.0", approx_bytes: 21964340, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "is-en", from: "is", to: "en", upstream_version: "2.0", approx_bytes: 36321986, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "it-en", from: "it", to: "en", upstream_version: "2.0", approx_bytes: 37088127, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ja-en", from: "ja", to: "en", upstream_version: "2.1", approx_bytes: 54769181, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "kn-en", from: "kn", to: "en", upstream_version: "1.0", approx_bytes: 22862463, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ko-en", from: "ko", to: "en", upstream_version: "2.1", approx_bytes: 54005366, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "lt-en", from: "lt", to: "en", upstream_version: "1.0", approx_bytes: 22672798, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "lv-en", from: "lv", to: "en", upstream_version: "1.0", approx_bytes: 22170805, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ml-en", from: "ml", to: "en", upstream_version: "1.0", approx_bytes: 23268070, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "mr-en", from: "mr", to: "en", upstream_version: "2.0", approx_bytes: 37105813, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ms-en", from: "ms", to: "en", upstream_version: "1.0", approx_bytes: 22315138, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "nb-en", from: "nb", to: "en", upstream_version: "2.0", approx_bytes: 22461294, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "nl-en", from: "nl", to: "en", upstream_version: "2.0", approx_bytes: 37231907, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "pl-en", from: "pl", to: "en", upstream_version: "2.0", approx_bytes: 37347607, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "pt-en", from: "pt", to: "en", upstream_version: "2.0", approx_bytes: 37013005, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ro-en", from: "ro", to: "en", upstream_version: "1.0", approx_bytes: 22633591, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ru-en", from: "ru", to: "en", upstream_version: "1.1", approx_bytes: 22530152, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "sk-en", from: "sk", to: "en", upstream_version: "1.0", approx_bytes: 22862457, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "sl-en", from: "sl", to: "en", upstream_version: "2.1", approx_bytes: 36685349, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "sq-en", from: "sq", to: "en", upstream_version: "1.0", approx_bytes: 22217767, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "sr-en", from: "sr", to: "en", upstream_version: "1.0", approx_bytes: 22591608, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "sv-en", from: "sv", to: "en", upstream_version: "1.0", approx_bytes: 22579780, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ta-en", from: "ta", to: "en", upstream_version: "2.0", approx_bytes: 37607349, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "te-en", from: "te", to: "en", upstream_version: "1.0", approx_bytes: 23013004, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "th-en", from: "th", to: "en", upstream_version: "2.0", approx_bytes: 37044272, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "tr-en", from: "tr", to: "en", upstream_version: "1.0", approx_bytes: 22614681, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "uk-en", from: "uk", to: "en", upstream_version: "1.1", approx_bytes: 21941581, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "ur-en", from: "ur", to: "en", upstream_version: "2.0", approx_bytes: 36158738, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "vi-en", from: "vi", to: "en", upstream_version: "1.0", approx_bytes: 21808485, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "zh-hans-en", from: "zh-Hans", to: "en", upstream_version: "2.1", approx_bytes: 54556676, vocab: "joint", tier: 1, source: "mozilla" },
    Pair { token: "zh-hant-en", from: "zh-Hant", to: "en", upstream_version: "2.0", approx_bytes: 51817972, vocab: "split", tier: 1, source: "mozilla" },
    Pair { token: "en-eo", from: "en", to: "eo", upstream_version: "opus-2020-05-23", approx_bytes: 48714915, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-ga", from: "en", to: "ga", upstream_version: "opus-2019-12-18", approx_bytes: 75143053, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-ht", from: "en", to: "ht", upstream_version: "opus+bt-2020-05-23", approx_bytes: 48752598, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-mg", from: "en", to: "mg", upstream_version: "opus-2020-01-08", approx_bytes: 74080402, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-mk", from: "en", to: "mk", upstream_version: "opus-2019-12-18", approx_bytes: 78135117, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-ny", from: "en", to: "ny", upstream_version: "opus-2020-01-08", approx_bytes: 76868268, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "en-tl", from: "en", to: "tl", upstream_version: "opus+bt-2020-02-26", approx_bytes: 75560165, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "eo-en", from: "eo", to: "en", upstream_version: "opus-2020-05-23", approx_bytes: 48714915, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "frm-en", from: "frm", to: "en", upstream_version: "opus2m-2020-08-01", approx_bytes: 77439940, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ga-en", from: "ga", to: "en", upstream_version: "opus-2019-12-18", approx_bytes: 75143053, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ha-en", from: "ha", to: "en", upstream_version: "opus+bt-2020-05-23", approx_bytes: 48786674, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ht-en", from: "ht", to: "en", upstream_version: "opus-2020-05-23", approx_bytes: 48752598, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ig-en", from: "ig", to: "en", upstream_version: "opus+bt-2020-05-23", approx_bytes: 48684319, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ka-en", from: "ka", to: "en", upstream_version: "opus-2019-12-18", approx_bytes: 78714083, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "la-en", from: "la", to: "en", upstream_version: "opus2m-2020-08-01", approx_bytes: 77439940, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "mg-en", from: "mg", to: "en", upstream_version: "opus-2020-01-09", approx_bytes: 74080402, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "mk-en", from: "mk", to: "en", upstream_version: "opus-2019-12-18", approx_bytes: 78135117, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "ny-en", from: "ny", to: "en", upstream_version: "opus-2020-01-16", approx_bytes: 76868268, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "rw-en", from: "rw", to: "en", upstream_version: "opus-2020-01-16", approx_bytes: 77133449, vocab: "joint", tier: 1, source: "opus-mt" },
    Pair { token: "tl-en", from: "tl", to: "en", upstream_version: "opus-2020-02-11", approx_bytes: 75560165, vocab: "joint", tier: 1, source: "opus-mt" },
];

/// Resolves a caller's pair token to the registry row, returning the
/// 'static row so nothing downstream holds a caller-shaped string.
/// LOOKUP, NEVER SPLIT: token grammar is not self-delimiting.
pub fn pair_by_token(candidate: &str) -> Option<&'static Pair> {
    PAIRS.iter().find(|p| p.token == candidate)
}

/// Pairs Mozilla publishes that this build EXCLUDES, with the reason.
/// Auditable: the provenance register must list exactly these too.
pub const EXCLUDED_PAIRS: &[(&str, &str, &str)] = &[
    ("az", "en", "alpha-only upstream (shipped to its nightly channel only)"),
    ("be", "en", "alpha-only upstream (shipped to its nightly channel only)"),
    ("en", "sq", "alpha-only upstream (shipped to its nightly channel only)"),
    ("mt", "en", "alpha-only upstream (shipped to its nightly channel only)"),
    ("nn", "en", "alpha-only upstream (shipped to its nightly channel only)"),
];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn pairs_are_english_anchored_and_named() {
        let codes: std::collections::HashSet<&str> =
            LANGUAGES.iter().map(|l| l.code).collect();
        for p in PAIRS {
            assert!(codes.contains(p.from), "{} unnamed", p.from);
            assert!(codes.contains(p.to), "{} unnamed", p.to);
            assert!(p.from == "en" || p.to == "en", "{} not en-anchored", p.token);
            assert_ne!(p.from, p.to);
            // The token is the LOWERCASED join: a script-tagged code
            // ("zh-Hans") keeps its case in `from`/`to`, which is what the
            // engine is handed, while the token stays a safe path segment.
            assert_eq!(
                p.token,
                format!("{}-{}", p.from, p.to).to_lowercase()
            );
            assert!(p.approx_bytes > 0);
            assert!(
                matches!(p.vocab, "joint" | "split"),
                "{}: unknown vocab layout {}", p.token, p.vocab
            );
            assert!(matches!(p.tier, 1 | 2), "{} bad tier", p.token);
            // The source vocabulary is CLOSED and tied to the tier: the
            // runtime selects the engine's GEMM precision by exact-matching
            // "opus-mt", so an unrecognized source silently routes a
            // calibrated model down the uncalibrated path.
            assert!(
                matches!(p.source, "mozilla" | "opus-mt"),
                "{}: unknown source {}", p.token, p.source
            );
            // Tier no longer follows source: OPUS-MT became FREE on
            // 2026-09-01, so a tier-1 pair may be either source. What
            // stays closed is the SOURCE set above, which is what selects
            // the GEMM precision; tier selects only the entitlement gate,
            // and nothing is gated today.
            assert!(
                p.tier != 2 || p.source == "opus-mt",
                "{}: a Premium pair must be opus-mt", p.token
            );
        }
    }
    #[test]
    fn lookup_is_exact_and_total() {
        assert!(pair_by_token("en-es").is_some());
        for miss in ["", "en-zz", "en-zz-hans", "EN-ES", "en", "en-es-fr-de"] {
            assert!(pair_by_token(miss).is_none(), "must miss {miss:?}");
        }
    }
    /// NO LANGUAGE STRADDLES THE TIERS. One language, one row, one
    /// button: a mixed-tier language could not be presented honestly
    /// by the packs panel, and `packs_status` reads the tier per
    /// language. The generator refuses to emit one; this pins it.
    #[test]
    fn no_language_mixes_tiers() {
        for lang in LANGUAGES {
            if lang.code == "en" {
                continue; // the pivot appears in every pair, both tiers
            }
            let tiers: std::collections::HashSet<u8> = PAIRS
                .iter()
                .filter(|p| p.from == lang.code || p.to == lang.code)
                .map(|p| p.tier)
                .collect();
            assert!(
                tiers.len() <= 1,
                "{} has directions in more than one tier: {:?}",
                lang.code,
                tiers
            );
        }
    }
    #[test]
    fn every_language_is_reachable() {
        for lang in LANGUAGES {
            assert!(
                PAIRS.iter().any(|p| p.from == lang.code || p.to == lang.code),
                "{} appears in no pair", lang.code
            );
        }
    }
}
