#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.md from the actual dependency tree.
#
# WHY A SCRIPT AND NOT A CHECKED-IN LIST. A hand-maintained inventory is wrong
# the first time a dependency is added and nobody notices, and an attribution
# file that is quietly incomplete is worse than none: it looks like diligence
# and is not. This reads `cargo metadata`, so it describes the tree that exists
# rather than the tree someone remembered.
#
# Uses --all-features deliberately. The public build has fewer dependencies
# than the chat build, and an inventory that only covered the default feature
# set would omit crates that ship in some binaries.
#
# Run: scripts/third-party-licenses.sh
# Then commit the result. CI can diff it to catch an un-regenerated file.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=THIRD_PARTY_LICENSES.md

cargo metadata --format-version 1 --all-features >/tmp/patanyx-meta.json

python3 - "$OUT" <<'PY'
import json, sys, collections, pathlib

out = pathlib.Path(sys.argv[1])
meta = json.load(open("/tmp/patanyx-meta.json"))

# Workspace members have no `source`; they are ours and are not third party.
ours = {p["id"] for p in meta["packages"] if p.get("source") is None}
deps = [p for p in meta["packages"] if p["id"] not in ours]
deps.sort(key=lambda p: (p["name"].lower(), p["version"]))

by_licence = collections.Counter()
missing = []
for p in deps:
    lic = p.get("license")
    if not lic and p.get("license_file"):
        lic = f"see {p['license_file']} in the crate source"
    if not lic:
        missing.append(p["name"])
        lic = "UNDECLARED"
    by_licence[lic] += 1

lines = []
lines.append("# Third-party licences")
lines.append("")
lines.append("Generated by `scripts/third-party-licenses.sh`. Do not edit by hand --")
lines.append("regenerate it, or it stops describing the tree it claims to describe.")
lines.append("")
lines.append(f"{len(deps)} third-party crates, resolved with `--all-features` so the")
lines.append("inventory covers every build configuration this project ships, not just")
lines.append("the default one.")
lines.append("")
lines.append("**A crate listed here is not necessarily a crate that ships.** This is the")
lines.append("UNION over every feature and every target platform `cargo metadata` knows")
lines.append("about, which is the safe direction for an attribution file -- it")
lines.append("over-reports rather than under-reports. It also means presence in this")
lines.append("table says nothing about whether a crate is compiled into any released")
lines.append("binary.")
lines.append("")
lines.append("That distinction is load-bearing when reading the licence column. As of")
lines.append("2026-07-29 the only GPL-family string anywhere below is `r-efi`'s")
lines.append("`MIT OR Apache-2.0 OR LGPL-2.1-or-later`; `r-efi` targets UEFI and is in")
lines.append("NEITHER shipped binary -- `cargo tree --target x86_64-unknown-linux-gnu -i")
lines.append("r-efi` and the same for `x86_64-pc-windows-msvc` both report no such")
lines.append("package. No copyleft code is distributed. Confirm the same way before")
lines.append("acting on a licence seen here, rather than assuming the table describes")
lines.append("what a user receives.")
lines.append("")
lines.append("PATANYX itself is Apache-2.0; see LICENSE. Attributions that must travel")
lines.append("with a redistribution -- bundled data, the platform engines -- are in")
lines.append("NOTICE, not here.")
lines.append("")
lines.append("## Licences in use")
lines.append("")
lines.append("| count | licence |")
lines.append("| ----: | ------- |")
for lic, n in sorted(by_licence.items(), key=lambda kv: (-kv[1], kv[0])):
    lines.append(f"| {n} | `{lic}` |")
lines.append("")

if missing:
    lines.append("## Crates with no declared licence")
    lines.append("")
    lines.append("These need a decision before release -- an undeclared licence is not a")
    lines.append("permissive one, it is an unknown one.")
    lines.append("")
    for name in sorted(missing):
        lines.append(f"- `{name}`")
    lines.append("")

lines.append("## Every crate")
lines.append("")
lines.append("| crate | version | licence |")
lines.append("| ----- | ------- | ------- |")
for p in deps:
    lic = p.get("license") or (
        f"see {p['license_file']}" if p.get("license_file") else "UNDECLARED"
    )
    lines.append(f"| `{p['name']}` | {p['version']} | {lic} |")
lines.append("")

out.write_text("\n".join(lines))
print(f"{out}: {len(deps)} crates, {len(by_licence)} distinct licence expressions")
if missing:
    print(f"WARNING: {len(missing)} crate(s) declare no licence: {', '.join(sorted(missing))}")
PY

rm -f /tmp/patanyx-meta.json
